# Generated by Django 6.0.3 on 2026-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(default='F', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_number',
            field=models.IntegerField(default=0, max_length=25),
        ),
    ]
