# Generated by Django 6.0.3 on 2026-03-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_grade_profile_role_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role_number',
            new_name='roll_number',
        ),
    ]
