# Generated by Django 6.0.3 on 2026-03-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
